### ISSUE TITLE
When selecting a new language it should replace the code in the textarea

### ISSUE THREAD

**Issue by Mogztter** [rouge-ruby/rouge.jneen.net#35]
As you can see, the language is randomly chosen on page load.
But then if I manually change the language from the `<select>`, the code code won't be replaced and, as a result, the syntax highlighting will not work:

![rouge-lang](https://user-images.githubusercontent.com/333276/71066368-c26af800-2172-11ea-8b4a-3cac6054bad6.gif)

I think we should replace the code in the textarea when selecting a new language.

**Comment by Mogztter** [comment]
There's actually already a pull request: #32

**Comment by pyrmont** [comment]
@Mogztter The new version of the dingus is [now live](http://rouge.jneen.net) and has this feature. 

It tries to do the replacement intelligently so that changing the language doesn't wipe the contents if you've started typing something in there (but it will if you've deleted everything).

Thank you for the suggestion and sorry it took a while!

**Comment by ggrossetie** [comment]
Awesome!
Just a small feedback, the vertical scroll bar on the highlighted text pane is set at the bottom while the source text scroll bar is set at the top.
For instance when you select CFScript.

Should I open an issue in the dingus repository? Should we archive this repository?

Thanks!

**Comment by pyrmont** [comment]
Can you open an issue there? This repo will probably be archived but no decision has been made on that yet.

**Comment by ggrossetie** [comment]
Done: https://github.com/rouge-ruby/dingus/issues/8
Thanks again for this new version, it looks faster :rocket:
